name: rapdle
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0-nullsafety.0
  http:
  chewie: ^1.2.2
  video_player: ^2.1.10
  flutter_svg: ^2.0.5
  cloud_firestore: ^4.15.9
  firebase_storage: ^11.6.10
  audioplayers: ^5.2.1
  firebase_core: ^2.27.1
  shared_preferences: ^2.2.2
  flutter_gif: ^0.0.4
  flutter_typeahead: ^4.8.0
  transparent_image: ^2.0.1
  flutter_image: ^4.0.0



  cupertino_icons: ^1.0.6
  lottie: ^3.1.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  fonts:
  - family: CrayonPaperDemoRegular
    fonts:
      - asset: assets/fonts/CrayonPaperDemoRegular.ttf
  - family: MiniBananaDemoRegular
    fonts:
      - asset: assets/fonts/MiniBananaDemoRegular.ttf
  assets:
    - assets/
    - assets/PlayAnimation.json
    - assets/WinAnimation.json
    - assets/LossAnimation.json
    - assets/fonts/CrayonPaperDemoRegular.ttf
    - assets/fonts/MiniBananaDemoRegular.ttf
    