name: rapdle
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0-nullsafety.0
  http:
  shared_preferences: ^2.0.0-nullsafety
  chewie: ^1.2.2
  video_player: ^2.1.10
  flutter_svg: ^2.0.5
  cloud_firestore: ^4.15.9
  firebase_storage: ^11.6.10
  audioplayers: ^5.2.1
  firebase_core: ^2.27.1



  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true
